//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 

namespace IMS.MD.v1p2
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("aggregationlevel", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class aggregationlevelType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("source", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class sourceType
    {

        /// <remarks/>
        public langstringType langstring;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("langstring", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class langstringType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("value", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class valueType
    {

        /// <remarks/>
        public langstringType langstring;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("annotation", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class annotationType
    {

        /// <remarks/>
        public personType person;

        /// <remarks/>
        public dateType date;

        /// <remarks/>
        public langType description;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("person", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class personType
    {

        /// <remarks/>
        public string vcard;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("date", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class dateType
    {

        /// <remarks/>
        public string datetime;

        /// <remarks/>
        public langType description;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("coverage", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class langType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("langstring")]
        public langstringType[] langstring;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlIgnore]
        public object documentation;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("catalogentry", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class cataloglangType
    {

        /// <remarks/>
        public string catalog;

        /// <remarks/>
        public langType entry;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("centity", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class centityType
    {

        /// <remarks/>
        public string vcard;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("classification", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class classificationType
    {

        /// <remarks/>
        public purposeType purpose;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taxonpath")]
        public taxonpathType[] taxonpath;

        /// <remarks/>
        public langType description;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keyword")]
        public langType[] keyword;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("purpose", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class purposeType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("taxonpath", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class taxonpathType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public taxonType taxon;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("taxon", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class taxonType
    {

        /// <remarks/>
        public string id;

        /// <remarks/>
        public langType entry;

        /// <remarks/>
        public taxonType taxon;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("context", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class contextType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("contribute", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class contributeType
    {

        /// <remarks/>
        public roleType role;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("centity")]
        public centityType[] centity;

        /// <remarks/>
        public dateType date;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("role", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class roleType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("copyrightandotherrestrictions", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class copyrightandotherrestrictionsType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("cost", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class costType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("difficulty", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class difficultyType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("educational", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class educationalType
    {

        /// <remarks/>
        public interactivitytypeType interactivitytype;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("learningresourcetype")]
        public learningresourcetypeType[] learningresourcetype;

        /// <remarks/>
        public interactivitylevelType interactivitylevel;

        /// <remarks/>
        public semanticdensityType semanticdensity;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("intendedenduserrole")]
        public intendedenduserroleType[] intendedenduserrole;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("context")]
        public contextType[] context;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("typicalagerange")]
        public langType[] typicalagerange;

        /// <remarks/>
        public difficultyType difficulty;

        /// <remarks/>
        public typicallearningtimeType typicallearningtime;

        /// <remarks/>
        public langType description;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public string[] language;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("interactivitytype", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class interactivitytypeType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("learningresourcetype", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class learningresourcetypeType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("interactivitylevel", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class interactivitylevelType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("semanticdensity", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class semanticdensityType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("intendedenduserrole", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class intendedenduserroleType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("typicallearningtime", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class typicallearningtimeType
    {

        /// <remarks/>
        public string datetime;

        /// <remarks/>
        public langType description;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("general", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class generalType
    {

        /// <remarks/>
        public string identifier;

        /// <remarks/>
        public langType title;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("catalogentry")]
        public cataloglangType[] catalogentry;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public string[] language;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public langType[] description;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keyword")]
        public langType[] keyword;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coverage")]
        public langType[] coverage;

        /// <remarks/>
        public structureType structure;

        /// <remarks/>
        public aggregationlevelType aggregationlevel;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("structure", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class structureType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("kind", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class kindType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("lifecycle", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class lifecycleType
    {

        /// <remarks/>
        public langType version;

        /// <remarks/>
        public statusType status;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contribute")]
        public contributeType[] contribute;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("status", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class statusType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("location", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class locationType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(locationTypeType.URI)]
        public locationTypeType type;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;

        public locationType()
        {
            this.type = locationTypeType.URI;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    public enum locationTypeType
    {

        /// <remarks/>
        URI,

        /// <remarks/>
        TEXT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("lom", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class lomType
    {

        /// <remarks/>
        public generalType general;

        /// <remarks/>
        public lifecycleType lifecycle;

        /// <remarks/>
        public metametadataType metametadata;

        /// <remarks/>
        public technicalType technical;

        /// <remarks/>
        public educationalType educational;

        /// <remarks/>
        public rightsType rights;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relation")]
        public relationType[] relation;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("annotation")]
        public annotationType[] annotation;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classification")]
        public classificationType[] classification;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("metametadata", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class metametadataType
    {

        /// <remarks/>
        public string identifier;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("catalogentry")]
        public cataloglangType[] catalogentry;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contribute")]
        public contributeType[] contribute;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadatascheme")]
        public string[] metadatascheme;

        /// <remarks/>
        public string language;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("technical", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class technicalType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("format")]
        public string[] format;

        /// <remarks/>
        public int size;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("location")]
        public locationType[] location;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requirement")]
        public requirementType[] requirement;

        /// <remarks/>
        public langType installationremarks;

        /// <remarks/>
        public langType otherplatformrequirements;

        /// <remarks/>
        public durationType duration;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("requirement", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class requirementType
    {

        /// <remarks/>
        public typeType type;

        /// <remarks/>
        public nameType name;

        /// <remarks/>
        public string minimumversion;

        /// <remarks/>
        public string maximumversion;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("type", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class typeType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("name", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class nameType
    {

        /// <remarks/>
        public sourceType source;

        /// <remarks/>
        public valueType value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("duration", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class durationType
    {

        /// <remarks/>
        public string datetime;

        /// <remarks/>
        public langType description;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("rights", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class rightsType
    {

        /// <remarks/>
        public costType cost;

        /// <remarks/>
        public copyrightandotherrestrictionsType copyrightandotherrestrictions;

        /// <remarks/>
        public langType description;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("relation", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class relationType
    {

        /// <remarks/>
        public kindType kind;

        /// <remarks/>
        public resourceType resource;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2")]
    [System.Xml.Serialization.XmlRootAttribute("resource", Namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", IsNullable = false)]
    public partial class resourceType
    {

        /// <remarks/>
        public string identifier;

        /// <remarks/>
        public langType description;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("catalogentry")]
        public cataloglangType[] catalogentry;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }
}