//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 

namespace IMS.MD.v1p3p2
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LOM.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    [System.Xml.Serialization.XmlRootAttribute("lom", Namespace = "http://ltsc.ieee.org/xsd/LOM", IsNullable = false)]
    public partial class LOMType : UnityEngine.ScriptableObject
    {

        /// <remarks/>
        public GeneralType general;

        /// <remarks/>
        public LifeCycleType lifeCycle;

        /// <remarks/>
        public MetaMetadataType metaMetadata;

        /// <remarks/>
        public TechnicalType technical;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("educational")]
        public EducationalType[] educational;

        /// <remarks/>
        public RightsType rights;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relation")]
        public RelationType[] relation;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("annotation")]
        public AnnotationType[] annotation;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classification")]
        public ClassificationType[] classification;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "General.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class GeneralType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identifier")]
        public IdentifierType[] identifier;

        /// <remarks/>
        public LangStringType title;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public string[] language;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public LangStringType[] description;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keyword")]
        public LangStringType[] keyword;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coverage")]
        public LangStringType[] coverage;

        /// <remarks/>
        public StructureType structure;

        /// <remarks/>
        public AggregationLevelType aggregationLevel;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Identifier.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class IdentifierType
    {

        /// <remarks/>
        public string catalog;

        /// <remarks/>
        public string entry;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Taxon.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class TaxonType
    {

        /// <remarks/>
        public string id;

        /// <remarks/>
        public LangStringType entry;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LangString.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class LangStringType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("string")]
        public LanguageStringType[] @string;

        /// <remarks/>
        [XmlIgnore]
        public string documentation;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LanguageString.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class LanguageStringType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "TaxonPath.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class TaxonPathType
    {

        /// <remarks/>
        public LangStringType source;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taxon")]
        public TaxonType[] taxon;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Purpose.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class PurposeType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public PurposeTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public PurposeType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum PurposeTypeValue
    {

        /// <remarks/>
        discipline,

        /// <remarks/>
        idea,

        /// <remarks/>
        prerequisite,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("educational objective")]
        educationalobjective,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("accessibility restrictions")]
        accessibilityrestrictions,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("educational level")]
        educationallevel,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("skill level")]
        skilllevel,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("security level")]
        securitylevel,

        /// <remarks/>
        competency,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Classification.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class ClassificationType
    {

        /// <remarks/>
        public PurposeType purpose;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taxonPath")]
        public TaxonPathType[] taxonPath;

        /// <remarks/>
        public LangStringType description;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keyword")]
        public LangStringType[] keyword;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Annotation.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class AnnotationType
    {

        /// <remarks/>
        public string entity;

        /// <remarks/>
        public DateTimeType date;

        /// <remarks/>
        public LangStringType description;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "DateTime.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class DateTimeType
    {

        /// <remarks/>
        public string dateTime;

        /// <remarks/>
        public LangStringType description;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Resource.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class ResourceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identifier")]
        public IdentifierType[] identifier;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public LangStringType[] description;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Kind.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class KindType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public KindTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public KindType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum KindTypeValue
    {

        /// <remarks/>
        ispartof,

        /// <remarks/>
        haspart,

        /// <remarks/>
        isversionof,

        /// <remarks/>
        hasversion,

        /// <remarks/>
        isformatof,

        /// <remarks/>
        hasformat,

        /// <remarks/>
        references,

        /// <remarks/>
        isreferencedby,

        /// <remarks/>
        isbasedon,

        /// <remarks/>
        isbasisfor,

        /// <remarks/>
        requires,

        /// <remarks/>
        isrequiredby,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Relation.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class RelationType
    {

        /// <remarks/>
        public KindType kind;

        /// <remarks/>
        public ResourceType resource;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "CopyrightAndOtherRestrictions.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class CopyrightAndOtherRestrictionsType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public CopyrightAndOtherRestrictionsTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public CopyrightAndOtherRestrictionsType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum CopyrightAndOtherRestrictionsTypeValue
    {

        /// <remarks/>
        yes,

        /// <remarks/>
        no,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Cost.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class CostType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public CostTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public CostType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum CostTypeValue
    {

        /// <remarks/>
        yes,

        /// <remarks/>
        no,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Rights.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class RightsType
    {

        /// <remarks/>
        public CostType cost;

        /// <remarks/>
        public CopyrightAndOtherRestrictionsType copyrightAndOtherRestrictions;

        /// <remarks/>
        public LangStringType description;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Difficulty.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class DifficultyType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public DifficultyTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public DifficultyType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum DifficultyTypeValue
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("very easy")]
        veryeasy,

        /// <remarks/>
        easy,

        /// <remarks/>
        medium,

        /// <remarks/>
        difficult,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("very difficult")]
        verydifficult,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Context.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class ContextType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public ContextTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public ContextType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum ContextTypeValue
    {

        /// <remarks/>
        school,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("higher education")]
        highereducation,

        /// <remarks/>
        training,

        /// <remarks/>
        other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "IntendedEndUserRole.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class IntendedEndUserRoleType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public IntendedEndUserRoleTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public IntendedEndUserRoleType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum IntendedEndUserRoleTypeValue
    {

        /// <remarks/>
        teacher,

        /// <remarks/>
        author,

        /// <remarks/>
        learner,

        /// <remarks/>
        manager,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "SemanticDensity.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class SemanticDensityType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public SemanticDensityTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public SemanticDensityType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum SemanticDensityTypeValue
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("very low")]
        verylow,

        /// <remarks/>
        low,

        /// <remarks/>
        medium,

        /// <remarks/>
        high,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("very high")]
        veryhigh,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "InteractivityLevel.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class InteractivityLevelType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public InteractivityLevelTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public InteractivityLevelType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum InteractivityLevelTypeValue
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("very low")]
        verylow,

        /// <remarks/>
        low,

        /// <remarks/>
        medium,

        /// <remarks/>
        high,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("very high")]
        veryhigh,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LearningResourceType.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class LearningResourceTypeType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public LearningResourceTypeTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public LearningResourceTypeType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum LearningResourceTypeTypeValue
    {

        /// <remarks/>
        exercise,

        /// <remarks/>
        simulation,

        /// <remarks/>
        questionnaire,

        /// <remarks/>
        diagram,

        /// <remarks/>
        figure,

        /// <remarks/>
        graph,

        /// <remarks/>
        index,

        /// <remarks/>
        slide,

        /// <remarks/>
        table,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("narrative text")]
        narrativetext,

        /// <remarks/>
        exam,

        /// <remarks/>
        experiment,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("problem statement")]
        problemstatement,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("self assessment")]
        selfassessment,

        /// <remarks/>
        lecture,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "InteractivityType.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class InteractivityTypeType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public InteractivityTypeTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public InteractivityTypeType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum InteractivityTypeTypeValue
    {

        /// <remarks/>
        active,

        /// <remarks/>
        expositive,

        /// <remarks/>
        mixed,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Educational.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class EducationalType
    {

        /// <remarks/>
        public InteractivityTypeType interactivityType;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("learningResourceType")]
        public LearningResourceTypeType[] learningResourceType;

        /// <remarks/>
        public InteractivityLevelType interactivityLevel;

        /// <remarks/>
        public SemanticDensityType semanticDensity;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("intendedEndUserRole")]
        public IntendedEndUserRoleType[] intendedEndUserRole;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("context")]
        public ContextType[] context;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("typicalAgeRange")]
        public LangStringType[] typicalAgeRange;

        /// <remarks/>
        public DifficultyType difficulty;

        /// <remarks/>
        public DurationType typicalLearningTime;

        /// <remarks/>
        public LangStringType description;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public string[] language;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Duration.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class DurationType
    {

        /// <remarks/>
        public string duration;

        /// <remarks/>
        public LangStringType description;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Name.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class NameType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public NameTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public NameType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum NameTypeValue
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("pc-dos")]
        pcdos,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ms-windows")]
        mswindows,

        /// <remarks/>
        macos,

        /// <remarks/>
        unix,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("multi-os")]
        multios,

        /// <remarks/>
        none,

        /// <remarks/>
        any,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("netscape communicator")]
        netscapecommunicator,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ms-internet explorer")]
        msinternetexplorer,

        /// <remarks/>
        opera,

        /// <remarks/>
        amaya,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Type.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class TypeType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public TypeTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public TypeType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum TypeTypeValue
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("operating system")]
        operatingsystem,

        /// <remarks/>
        browser,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "OrComposite.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class OrCompositeType
    {

        /// <remarks/>
        public TypeType type;

        /// <remarks/>
        public NameType name;

        /// <remarks/>
        public string minimumVersion;

        /// <remarks/>
        public string maximumVersion;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Requirement.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class RequirementType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("orComposite")]
        public OrCompositeType[] orComposite;

        /// <remarks/>
        [XmlIgnore]
        public string documentation;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Technical.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class TechnicalType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("format")]
        public string[] format;

        /// <remarks/>
        public string size;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("location")]
        public string[] location;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requirement")]
        public RequirementType[] requirement;

        /// <remarks/>
        public LangStringType installationRemarks;

        /// <remarks/>
        public LangStringType otherPlatformRequirements;

        /// <remarks/>
        public DurationType duration;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "RoleMetaMetadata.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class RoleMetaMetadataType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public RoleMetaMetadataTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public RoleMetaMetadataType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum RoleMetaMetadataTypeValue
    {

        /// <remarks/>
        creator,

        /// <remarks/>
        validator,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ContributeMetaMetadata.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class ContributeMetaMetadataType
    {

        /// <remarks/>
        public RoleMetaMetadataType role;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity")]
        public string[] entity;

        /// <remarks/>
        public DateTimeType date;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "MetaMetadata.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class MetaMetadataType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identifier")]
        public IdentifierType[] identifier;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contribute")]
        public ContributeMetaMetadataType[] contribute;

        /// <remarks/>
        // Advertencia CODEGEN: El atributo DefaultValue de los miembros del tipo System.String[] no es compatible con esta versión de .Net Framework.
        // Advertencia CODEGEN: Esta versión de .Net Framework no admite el atributo 'default' en elementos tipo matriz. Se omite el atributo default='LOMv1.0' en el nombre de elemento='metadataschema'.
        [System.Xml.Serialization.XmlElementAttribute("metadataschema")]
        public string[] metadataschema;

        /// <remarks/>
        public string language;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "RoleLifeCycle.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class RoleLifeCycleType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public RoleLifeCycleTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public RoleLifeCycleType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum RoleLifeCycleTypeValue
    {

        /// <remarks/>
        author,

        /// <remarks/>
        publisher,

        /// <remarks/>
        unknown,

        /// <remarks/>
        initiator,

        /// <remarks/>
        terminator,

        /// <remarks/>
        validator,

        /// <remarks/>
        editor,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("graphical designer")]
        graphicaldesigner,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("technical implementer")]
        technicalimplementer,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("content provider")]
        contentprovider,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("technical validator")]
        technicalvalidator,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("educational validator")]
        educationalvalidator,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("script writer")]
        scriptwriter,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("instructional designer")]
        instructionaldesigner,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("subject matter expert")]
        subjectmatterexpert,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ContributeLifeCycle.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class ContributeLifeCycleType
    {

        /// <remarks/>
        public RoleLifeCycleType role;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity")]
        public string[] entity;

        /// <remarks/>
        public DateTimeType date;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Status.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class StatusType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public StatusTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public StatusType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum StatusTypeValue
    {

        /// <remarks/>
        draft,

        /// <remarks/>
        final,

        /// <remarks/>
        revised,

        /// <remarks/>
        unavailable,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LifeCycle.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class LifeCycleType
    {

        /// <remarks/>
        public LangStringType version;

        /// <remarks/>
        public StatusType status;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contribute")]
        public ContributeLifeCycleType[] contribute;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AggregationLevel.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class AggregationLevelType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public AggregationLevelTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public AggregationLevelType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum AggregationLevelTypeValue
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Structure.Type", Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public partial class StructureType
    {

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("LOMv1.0")]
        public string source;

        /// <remarks/>
        public StructureTypeValue value;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified;

        public StructureType()
        {
            this.source = "LOMv1.0";
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ltsc.ieee.org/xsd/LOM")]
    public enum StructureTypeValue
    {

        /// <remarks/>
        atomic,

        /// <remarks/>
        collection,

        /// <remarks/>
        networked,

        /// <remarks/>
        hierarchical,

        /// <remarks/>
        linear,
    }

}