//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="LOM.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
[System.Xml.Serialization.XmlRootAttribute("lom", Namespace="http://ltsc.ieee.org/xsd/LOM", IsNullable=false)]
public partial class LOMType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("annotation", typeof(AnnotationType))]
    [System.Xml.Serialization.XmlElementAttribute("classification", typeof(ClassificationType))]
    [System.Xml.Serialization.XmlElementAttribute("educational", typeof(EducationalType))]
    [System.Xml.Serialization.XmlElementAttribute("general", typeof(GeneralType))]
    [System.Xml.Serialization.XmlElementAttribute("lifeCycle", typeof(LifeCycleType))]
    [System.Xml.Serialization.XmlElementAttribute("metaMetadata", typeof(MetaMetadataType))]
    [System.Xml.Serialization.XmlElementAttribute("relation", typeof(RelationType))]
    [System.Xml.Serialization.XmlElementAttribute("rights", typeof(RightsType))]
    [System.Xml.Serialization.XmlElementAttribute("technical", typeof(TechnicalType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Annotation.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class AnnotationType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(DateTimeType))]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("entity", typeof(CharacterStringType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="DateTime.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class DateTimeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("dateTime", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(LangStringType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="CharacterString.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class CharacterStringType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Taxon.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class TaxonType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("entry", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("id", typeof(CharacterStringType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="LangString.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class LangStringType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("string")]
    public LanguageStringType[] @string;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="LanguageString.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class LanguageStringType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string language;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="TaxonPath.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class TaxonPathType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("taxon", typeof(TaxonType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Purpose.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class PurposeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType23[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType23 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Classification.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class ClassificationType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("keyword", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("purpose", typeof(PurposeType))]
    [System.Xml.Serialization.XmlElementAttribute("taxonPath", typeof(TaxonPathType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType24[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType24 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    description,
    
    /// <remarks/>
    keyword,
    
    /// <remarks/>
    purpose,
    
    /// <remarks/>
    taxonPath,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Resource.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class ResourceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("identifier", typeof(IdentifierType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Identifier.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class IdentifierType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("catalog", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("entry", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    catalog,
    
    /// <remarks/>
    entry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Kind.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class KindType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType22[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType22 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Relation.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class RelationType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("kind", typeof(KindType))]
    [System.Xml.Serialization.XmlElementAttribute("resource", typeof(ResourceType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="CopyrightAndOtherRestrictions.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class CopyrightAndOtherRestrictionsType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType21[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType21 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Cost.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class CostType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType20[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType20 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Rights.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class RightsType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("copyrightAndOtherRestrictions", typeof(CopyrightAndOtherRestrictionsType))]
    [System.Xml.Serialization.XmlElementAttribute("cost", typeof(CostType))]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(LangStringType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Difficulty.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class DifficultyType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType18[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType18 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Context.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class ContextType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType17[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType17 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="IntendedEndUserRole.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class IntendedEndUserRoleType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType16[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType16 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="SemanticDensity.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class SemanticDensityType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType15[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType15 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="InteractivityLevel.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class InteractivityLevelType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType14[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType14 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="LearningResourceType.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class LearningResourceTypeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType13[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType13 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="InteractivityType.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class InteractivityTypeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType12[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType12 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Educational.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class EducationalType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("context", typeof(ContextType))]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("difficulty", typeof(DifficultyType))]
    [System.Xml.Serialization.XmlElementAttribute("intendedEndUserRole", typeof(IntendedEndUserRoleType))]
    [System.Xml.Serialization.XmlElementAttribute("interactivityLevel", typeof(InteractivityLevelType))]
    [System.Xml.Serialization.XmlElementAttribute("interactivityType", typeof(InteractivityTypeType))]
    [System.Xml.Serialization.XmlElementAttribute("language", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("learningResourceType", typeof(LearningResourceTypeType))]
    [System.Xml.Serialization.XmlElementAttribute("semanticDensity", typeof(SemanticDensityType))]
    [System.Xml.Serialization.XmlElementAttribute("typicalAgeRange", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("typicalLearningTime", typeof(DurationType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType19[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Duration.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class DurationType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("duration", typeof(CharacterStringType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType19 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    context,
    
    /// <remarks/>
    description,
    
    /// <remarks/>
    difficulty,
    
    /// <remarks/>
    intendedEndUserRole,
    
    /// <remarks/>
    interactivityLevel,
    
    /// <remarks/>
    interactivityType,
    
    /// <remarks/>
    language,
    
    /// <remarks/>
    learningResourceType,
    
    /// <remarks/>
    semanticDensity,
    
    /// <remarks/>
    typicalAgeRange,
    
    /// <remarks/>
    typicalLearningTime,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Name.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class NameType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType9[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType9 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Type.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class TypeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType8[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType8 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="OrComposite.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class OrCompositeType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("maximumVersion", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("minimumVersion", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("name", typeof(NameType))]
    [System.Xml.Serialization.XmlElementAttribute("type", typeof(TypeType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType10[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType10 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    maximumVersion,
    
    /// <remarks/>
    minimumVersion,
    
    /// <remarks/>
    name,
    
    /// <remarks/>
    type,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Requirement.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class RequirementType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("orComposite", typeof(OrCompositeType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Technical.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class TechnicalType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("duration", typeof(DurationType))]
    [System.Xml.Serialization.XmlElementAttribute("format", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("installationRemarks", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("location", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("otherPlatformRequirements", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("requirement", typeof(RequirementType))]
    [System.Xml.Serialization.XmlElementAttribute("size", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType11[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType11 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    duration,
    
    /// <remarks/>
    format,
    
    /// <remarks/>
    installationRemarks,
    
    /// <remarks/>
    location,
    
    /// <remarks/>
    otherPlatformRequirements,
    
    /// <remarks/>
    requirement,
    
    /// <remarks/>
    size,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="RoleMetaMetadata.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class RoleMetaMetadataType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType6[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType6 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="ContributeMetaMetadata.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class ContributeMetaMetadataType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(DateTimeType))]
    [System.Xml.Serialization.XmlElementAttribute("entity", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("role", typeof(RoleMetaMetadataType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="MetaMetadata.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class MetaMetadataType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("contribute", typeof(ContributeMetaMetadataType))]
    [System.Xml.Serialization.XmlElementAttribute("identifier", typeof(IdentifierType))]
    [System.Xml.Serialization.XmlElementAttribute("language", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("metadataschema", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType7[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType7 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    contribute,
    
    /// <remarks/>
    identifier,
    
    /// <remarks/>
    language,
    
    /// <remarks/>
    metadataschema,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="RoleLifeCycle.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class RoleLifeCycleType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType5[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType5 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="ContributeLifeCycle.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class ContributeLifeCycleType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(DateTimeType))]
    [System.Xml.Serialization.XmlElementAttribute("entity", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("role", typeof(RoleLifeCycleType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Status.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class StatusType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType4[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType4 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="LifeCycle.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class LifeCycleType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("contribute", typeof(ContributeLifeCycleType))]
    [System.Xml.Serialization.XmlElementAttribute("status", typeof(StatusType))]
    [System.Xml.Serialization.XmlElementAttribute("version", typeof(LangStringType))]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="AggregationLevel.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class AggregationLevelType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType2[] ItemsElementName;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType2 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="Structure.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class StructureType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    value,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="General.Type", Namespace="http://ltsc.ieee.org/xsd/LOM")]
public partial class GeneralType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("aggregationLevel", typeof(AggregationLevelType))]
    [System.Xml.Serialization.XmlElementAttribute("coverage", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("identifier", typeof(IdentifierType))]
    [System.Xml.Serialization.XmlElementAttribute("keyword", typeof(LangStringType))]
    [System.Xml.Serialization.XmlElementAttribute("language", typeof(CharacterStringType))]
    [System.Xml.Serialization.XmlElementAttribute("structure", typeof(StructureType))]
    [System.Xml.Serialization.XmlElementAttribute("title", typeof(LangStringType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType3[] ItemsElementName;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ltsc.ieee.org/xsd/LOM", IncludeInSchema=false)]
public enum ItemsChoiceType3 {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    aggregationLevel,
    
    /// <remarks/>
    coverage,
    
    /// <remarks/>
    description,
    
    /// <remarks/>
    identifier,
    
    /// <remarks/>
    keyword,
    
    /// <remarks/>
    language,
    
    /// <remarks/>
    structure,
    
    /// <remarks/>
    title,
}
